export default {
  header: "My Weathercoat Page",
  view: "Weathercoat",
  humidity: "",
  realFeel: "",
  realTemp: "",
  visibility: "",
  today_icon: "",
  wind_direction: "",
  wind_speed: "",
  wind_gust: "",
  alert: "",
  restOfDays: [
    { date: "", temp: "", icon: "" },
    { date: "", temp: "", icon: "" },
    { date: "", temp: "", icon: "" },
    { date: "", temp: "", icon: "" },
    { date: "", temp: "", icon: "" }
  ],
  forecast_day1: { date: "", temp: "", icon: "" },
  forecast_day2: { date: "", temp: "", icon: "" },
  forecast_day3: { date: "", temp: "", icon: "" },
  forecast_day4: { date: "", temp: "", icon: "" },
  forecast_day5: { date: "", temp: "", icon: "" },
  weather_location: "",
  weather_city: "",
  weather_state: "",
  weather_country: "",
  username: "",
  avatar: "cat",
  load_avatar: "",
  lat: "",
  lon: "",
  error: ""
};
